name: Resuable Deployment Workflow
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string

jobs:
  shared-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Target Environment
        run: |
          echo "Executing Central Deployment Logic..."
          echo "Deploying Application to: ${{ inputs.target-environment }}"


