name: Marketplace Actions Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout-and-list-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      
      - name: List Files in Repository
        run: |
          echo "Current Working Directory:"
          pwd
          echo "Files in this Repository:"
          ls -la


