name: Matrix Strategy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  multi-env-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20]
    
    runs-on: ${{ matrix.os }}
    
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
       - name: Setup Node.js Version
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
       - name: verify OS and Node Version
         run: |
           echo "Running on OS: ${{ matrix.os }}"
           echo "Node Version inside container:"
           node -v
