name: Multi Job CI CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Testing
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: echo "Running Application Unit Tests... All Tests Passed!"

#Job 2: Building (after completion of test-job, it willl started)

  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Build Application Package
        run: echo "Building Docker Image / App Package..."

# Job 3: Deploying(After completion of build-job, it iwll starts)
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: echo "Deploying code to AWS Production Server!"


