name: Github Secrets Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test Database Connection with Secret
        env:
          DB_PASS: ${{ secrets.MY_DB_PASSWORD  }}
        run: |
          echo "Connecting to Database..."
          echo "The Database password is: $DB_PASS"

